import pandas as pd
df = pd.read_csv(r"C:\Users\ANUSHA\OneDrive\INTERNSHIP\PYTHON\panda\response for employee data.csv")
print(df)
print(df.head())
print(df.tail())
print(df.columns)
print(df.shape)
print(df.info())
print(df.describe())
print(df[['Name', 'salary']])
print(df.iloc[0])
df['salary'] = df['salary'] .str.replace(',', '').astype(int)
print(df[df['salary'] > 50000])
print(df[df['Age'] > 25])
print(df[df['Experience'] > 5]) 